### ISSUE TITLE
How to know microgateway version that is deployed in ibmcloud

### ISSUE THREAD

**Issue by satishbkodali** [swilliams11/apigee-microgateway-bluemix#2]
Sean,
How to know the microgateway version that is deployed in ibmcloud?
Tried to ssh to the container where it is deployed.

`vcap@3542c013-7aa4-4644-4f45-36ae:~$ edgemicro -v
bash: edgemicro: command not found`

How to get version number that it is deployed?

**Comment by swilliams11** [comment]
IBM cloud installs to a specific directory on the container. If you find the container directory where Edge Microgateway is installed, then you can run the command from that directory.  Can you try that?
